### ISSUE TITLE
Long pressing the sticker in sticker packs on android crashes the browser

### ISSUE THREAD

**Issue by aha999** [signalstickers/signalstickers#302] opened 2020-10-03 05:53 UTC
When using the website on Android and opening a sticker pack, long pressing the icon either freezes the Firefox browser for a couple of seconds before showing a context menu, or it crashes it. I didn't try on other browsers.

**Comment by romainricard** [comment] 2020-10-04 09:50
Can you give more details about your configuration? I can't reproduce, either on Firefox (`org.mozilla.firefox 81.1.1`) or Firefox Focus (`org.mozilla.focus 8.8.1`) (Android 10)

**Comment by aha999** [comment] 2020-10-17 10:57
Firefox 81.1.4, Android 10 (LineageOS 17.1)

**Comment by romainricard** [comment] 2020-10-24 12:44
I missed the `81.1.4`, but I've updated to `81.1.5` and still can't reproduce. I think this is more on Firefox side (or even Android), as the website uses regular `<a>` tags, so I can't really see why it would crash the browser. Closing for now, if you keep having this issue after Firefox reinstall/update, feel free to reopen it! Thanks again for the report.

**Closed by romainricard** 2020-10-24 12:44 UTC
